# Common configuration shared between all applications
configserver:
  name: Docker JHipster Registry
  status: Connected to the JHipster Registry running in Docker

jhipster:
  security:
    authentication:
      jwt:
        # secret key which should be base64 encoded and changed in production
        base64-secret: ZDZlNWVmMmM2MmUyODVmOTRlZjc2ZDE2NWQyZGUzMmUyM2IwN2MwZTljZDEyM2Y5OGY5MTMwZmYyOTQ4M2I2MzdjMTMxZWU3NDE3NzBiNTQxYWQwY2MzNDQwNWJlNDgwMTYzN2YzOTgzY2YzYmIyNWJhODFkNmUwZDQzMjJlY2U=

eureka:
  client:
    service-url:
      defaultZone: http://admin:${jhipster.registry.password}@localhost:8761/eureka/
