# Common configuration shared between all applications
configserver:
  name: Docker JHipster Registry
  status: Connected to the JHipster Registry running in Docker

jhipster:
  security:
    authentication:
      jwt:
        # secret key which should be base64 encoded and changed in production
        base64-secret: ZTMzYjBkN2U5M2EzY2ExOTZhNzdiYzUzYmEwNTkwMWFhMmY4ZjQwMGY3OTc4ZTBiMThlZDk4MjM5MGMwYWU0ZjY5NWMzN2QyNTU2ZjNjODcwYTEyNzhkMGZhYzFiY2RlZDkxZWMzYTg0ZGZlOTNjNzQ3MmI1OTE0ZDkzOGM4OTE=

eureka:
  client:
    service-url:
      defaultZone: http://admin:${jhipster.registry.password}@localhost:8761/eureka/
